### ISSUE TITLE
Fix windows powershell downlaoder

### ISSUE THREAD

**Issue by semsion** [joergi/HackspaceMagazineDownloader#23]
~~Filenames do not match up and once downloader does begin, fails on both platforms.~~

Fix Windows downloading, as it needs to be done in MagPiDownloader https://github.com/joergi/MagPiDownloader/issues/83

**Comment by joergi** [comment]
it should be fixed for Linux, right?
I'm having problem with fixing the Windows one, I'm not a windows developer...
