### ISSUE TITLE
Remove issues.txt

### ISSUE THREAD

**Issue by quotschmacher** [joergi/HackspaceMagazineDownloader#7]
What is the neccessarity of issues.txt? ou could simply iterate until a call to `https://.../issues/33` (not existing at the moment i'm writing this) give you a result that differs from 200.

**Comment by joergi** [comment]
Thx, for the issue @quotschmacher , I will have look for it.
There was a time, when the script needed it. There was `for loop,` so we were not getting a out of bound exception.
I will have look for the Linux / Mac scripts, and maybe @Rubemlrm can have a look for the windows scripts?

**Comment by joergi** [comment]
Hey @quotschmacher,
I guess we will keep it for now, as we will use this number for automatic testing
At the moment we have the number in [testing.yml](https://github.com/joergi/HackspaceMagazineDownloader/blob/master/.github/workflows/testing.yml#L57) hard written, but it should use at the end the issue number automatically.

If you have better ideas, feel free to answer here, but at the moment I will close this ticket.
